"use client";

import Link from "next/link";
import { useState } from "react";
import { AdminActionModal } from "@/components/admin/admin-action-modal";
import { StatusBadge } from "@/components/seller/status-badge";
import { useAdmin } from "@/context/admin-context";
import { useSeller } from "@/context/seller-context";
import type { Withdrawal, WithdrawalStatus } from "@/types";
import { formatCurrency } from "@/utils/format-currency";

export function AdminWithdrawalsPage() {
  const { seller, withdrawals, updateWithdrawal } = useSeller(); const { recordAction } = useAdmin(); const [action, setAction] = useState<{ withdrawal: Withdrawal; status: WithdrawalStatus; label: string; requireReason: boolean } | null>(null); const [notice, setNotice] = useState("");
  function apply(reason: string) { if (!action) return; updateWithdrawal(action.withdrawal.id, { status: action.status, processedAt: action.status === "Paid" || action.status === "Rejected" ? new Date().toISOString() : undefined, reason: reason || undefined }); recordAction({ actionType: action.label, entityType: "withdrawal", entityId: action.withdrawal.id, reason: reason || "Withdrawal approved", previousValue: action.withdrawal.status, newValue: action.status }); setNotice(`${action.label} completed.`); setAction(null); }
  return <><div><p className="text-sm font-bold text-emerald-700">Seller payouts</p><h1 className="mt-1 text-3xl font-black">Withdrawals</h1><p className="mt-2 text-sm text-slate-500">Frontend requests only. Real financial account details are never shown or stored.</p></div>{notice ? <div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{notice}</div> : null}<div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Withdrawal", "Seller", "Amount", "Destination type", "Requested", "Status", "Processed", "Actions"].map((item) => <th key={item} className="px-5 py-4">{item}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{withdrawals.map((withdrawal) => <tr key={withdrawal.id}><td className="px-5 py-4 font-bold">{withdrawal.id}</td><td className="px-5 py-4">{seller.storeName}</td><td className="px-5 py-4 font-black">{formatCurrency(withdrawal.amount)}</td><td className="px-5 py-4">{withdrawal.method}</td><td className="px-5 py-4">{new Date(withdrawal.createdAt).toLocaleDateString("en-GH")}</td><td className="px-5 py-4"><StatusBadge status={withdrawal.status} /></td><td className="px-5 py-4">{withdrawal.processedAt ? new Date(withdrawal.processedAt).toLocaleDateString("en-GH") : "—"}</td><td className="px-5 py-4"><div className="flex gap-2"><Link href={`/admin/sellers/${seller.id}`} className="rounded-lg border px-3 py-2 text-xs font-bold">View Seller</Link><button type="button" onClick={() => setAction({ withdrawal, status: "Approved", label: "Approve Withdrawal", requireReason: false })} className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Approve</button><button type="button" onClick={() => setAction({ withdrawal, status: "Rejected", label: "Reject Withdrawal", requireReason: true })} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700">Reject</button></div></td></tr>)}</tbody></table>{withdrawals.length ? null : <p className="p-12 text-center text-sm text-slate-500">No withdrawal requests.</p>}</div><AdminActionModal open={Boolean(action)} title={action?.label ?? "Withdrawal action"} description="No real payment destination information is used by this frontend action." confirmLabel={action?.label ?? "Confirm"} requireReason={action?.requireReason} tone={action?.status === "Rejected" ? "danger" : "default"} onClose={() => setAction(null)} onConfirm={apply} /></>;
}
