"use client";

import Link from "next/link";
import { useState } from "react";
import { StatusBadge } from "@/components/seller/status-badge";
import { useAdmin } from "@/context/admin-context";
import { useOrders } from "@/hooks/use-orders";
import { formatCurrency } from "@/utils/format-currency";

export function AdminBuyersPage() {
  const { buyers, disputes } = useAdmin(); const { orders } = useOrders(); const [status, setStatus] = useState(""); const [search, setSearch] = useState(""); const visible = buyers.filter((buyer) => !search || [buyer.id, buyer.name, buyer.email, buyer.phone].some((value) => value.toLowerCase().includes(search.toLowerCase()))).filter((buyer) => !status || buyer.status === status);
  return <><div><p className="text-sm font-bold text-emerald-700">Customer accounts</p><h1 className="mt-1 text-3xl font-black">Buyers</h1><p className="mt-2 text-sm text-slate-500">Buyer activity, spending and account status.</p></div><div className="mt-6 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:flex-row"><label className="flex-1 text-xs font-bold">Search<input value={search} onChange={(event) => setSearch(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal" /></label><label className="text-xs font-bold sm:w-56">Status<select value={status} onChange={(event) => setStatus(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal"><option value="">All</option><option>Active</option><option>Suspended</option><option>Banned</option></select></label></div><div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Buyer", "Contact", "Orders", "Total spent", "Disputes", "Status", "Joined", ""].map((item) => <th key={item} className="px-5 py-4">{item}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{visible.map((buyer) => { const buyerOrders = orders.filter((order) => order.buyer.email === buyer.email); return <tr key={buyer.id}><td className="px-5 py-4"><b>{buyer.name}</b><span className="block text-xs text-slate-400">{buyer.id}</span></td><td className="px-5 py-4 text-xs">{buyer.email}<br />{buyer.phone}</td><td className="px-5 py-4">{buyerOrders.length}</td><td className="px-5 py-4 font-bold">{formatCurrency(buyerOrders.reduce((sum, order) => sum + order.total, 0))}</td><td className="px-5 py-4">{disputes.filter((dispute) => dispute.buyerName === buyer.name).length}</td><td className="px-5 py-4"><StatusBadge status={buyer.status} /></td><td className="px-5 py-4 text-xs">{new Date(buyer.joinedAt).toLocaleDateString("en-GH")}</td><td className="px-5 py-4"><Link href={`/admin/buyers/${buyer.id}`} className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">View</Link></td></tr>; })}</tbody></table></div></>;
}
