"use client";

import Link from "next/link";
import { useState } from "react";
import { useAdmin } from "@/context/admin-context";

export function AdminMessagesPage() {
  const { disputes } = useAdmin();
  const conversations = [{ id: "support-001", user: "Ama Boateng", role: "Buyer", related: "Product listing question", lastMessage: "I need help understanding a refund update.", unread: 1, reason: "Support request", messages: ["Buyer: I need help understanding a refund update.", "Admin: We have received your request and will review it."] }, ...disputes.map((dispute) => ({ id: `conversation-${dispute.id}`, user: `${dispute.buyerName} and ${dispute.sellerName}`, role: "Dispute parties", related: dispute.orderId, lastMessage: dispute.reason, unread: dispute.status === "Under Review" ? 2 : 0, reason: "Active dispute", messages: [`Buyer: ${dispute.buyerStatement}`, `Seller: ${dispute.sellerStatement}`] }))];
  const [activeId, setActiveId] = useState(conversations[0]?.id ?? ""); const [reply, setReply] = useState(""); const [sent, setSent] = useState<string[]>([]); const active = conversations.find((item) => item.id === activeId) ?? conversations[0];
  return <><div><p className="text-sm font-bold text-emerald-700">Scoped support access</p><h1 className="mt-1 text-3xl font-black">Admin messages</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Only support conversations, reported conversations and active-dispute conversations are shown. Private marketplace chats are not silently exposed.</p></div><div className="mt-6 grid min-h-[620px] overflow-hidden rounded-2xl border border-slate-200 bg-white lg:grid-cols-[22rem_1fr]"><aside className="border-r border-slate-200"><div className="border-b p-4 font-black">Eligible conversations</div>{conversations.map((item) => <button key={item.id} type="button" onClick={() => setActiveId(item.id)} className={`w-full border-b border-slate-100 p-4 text-left ${item.id === active?.id ? "bg-emerald-50" : "hover:bg-slate-50"}`}><div className="flex justify-between"><p className="text-sm font-black">{item.user}</p>{item.unread ? <span className="grid size-5 place-items-center rounded-full bg-rose-600 text-[10px] text-white">{item.unread}</span> : null}</div><p className="mt-1 text-xs font-bold text-emerald-700">{item.role} · {item.reason}</p><p className="mt-2 truncate text-xs text-slate-500">{item.lastMessage}</p><p className="mt-1 text-[10px] text-slate-400">{item.related}</p></button>)}</aside>{active ? <section className="flex min-w-0 flex-col"><header className="border-b p-4"><h2 className="font-black">{active.user}</h2><p className="mt-1 text-xs text-slate-500">{active.reason} · {active.related}</p></header><div className="flex-1 space-y-3 bg-slate-50/60 p-5">{[...active.messages, ...sent].map((message, index) => <div key={`${message}-${index}`} className={`max-w-2xl rounded-2xl p-4 text-sm ${message.startsWith("Admin:") ? "ml-auto bg-emerald-700 text-white" : "border border-slate-200 bg-white"}`}>{message}</div>)}</div><form onSubmit={(event) => { event.preventDefault(); if (!reply.trim()) return; setSent((items) => [...items, `Admin: ${reply.trim()}`]); setReply(""); }} className="flex gap-3 border-t p-4"><label htmlFor="admin-support-reply" className="sr-only">Support reply</label><input id="admin-support-reply" value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Write a support response" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-4 py-3 text-sm" /><button type="submit" className="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-black text-white">Send</button>{active.reason === "Active dispute" ? <Link href={`/admin/disputes/${active.id.replace("conversation-", "")}`} className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold">Open Dispute</Link> : null}</form></section> : null}</div></>;
}
