"use client";

import Link from "next/link";
import { useState } from "react";
import { StatusBadge } from "@/components/seller/status-badge";
import { useAdmin } from "@/context/admin-context";
import { formatCurrency } from "@/utils/format-currency";

export function AdminDisputesPage() {
  const { disputes } = useAdmin(); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const visible = disputes.filter((dispute) => !search || [dispute.id, dispute.orderId, dispute.buyerName, dispute.sellerName, dispute.reason].some((value) => value.toLowerCase().includes(search.toLowerCase()))).filter((dispute) => !status || dispute.status === status);
  return <><div><p className="text-sm font-bold text-emerald-700">Case management</p><h1 className="mt-1 text-3xl font-black">Disputes</h1><p className="mt-2 text-sm text-slate-500">Review evidence, hold payments and record fair marketplace decisions.</p></div><div className="mt-6 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:flex-row"><label className="flex-1 text-xs font-bold">Search<input value={search} onChange={(event) => setSearch(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal" /></label><label className="text-xs font-bold sm:w-64">Status<select value={status} onChange={(event) => setStatus(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal"><option value="">All</option>{["Open", "Under Review", "Waiting for Buyer", "Waiting for Seller", "Resolved for Buyer", "Resolved for Seller", "Partially Resolved", "Closed"].map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Dispute", "Order", "Buyer", "Seller", "Reason", "Amount", "Status", "Opened", "Updated", ""].map((item) => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{visible.map((dispute) => <tr key={dispute.id}><td className="px-4 py-4 font-black">{dispute.id}</td><td className="px-4 py-4">{dispute.orderId}</td><td className="px-4 py-4">{dispute.buyerName}</td><td className="px-4 py-4">{dispute.sellerName}</td><td className="max-w-64 truncate px-4 py-4">{dispute.reason}</td><td className="px-4 py-4 font-bold">{formatCurrency(dispute.amount)}</td><td className="px-4 py-4"><StatusBadge status={dispute.status} /></td><td className="px-4 py-4 text-xs">{new Date(dispute.openedAt).toLocaleDateString("en-GH")}</td><td className="px-4 py-4 text-xs">{new Date(dispute.updatedAt).toLocaleDateString("en-GH")}</td><td className="px-4 py-4"><Link href={`/admin/disputes/${dispute.id}`} className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">View Details</Link></td></tr>)}</tbody></table>{visible.length ? null : <p className="p-12 text-center text-sm text-slate-500">No disputes match this filter.</p>}</div></>;
}
