"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useMemo, useState, useSyncExternalStore } from "react";
import { useAdmin } from "@/context/admin-context";
import { useCategories } from "@/context/category-context";
import type { Category } from "@/types";
import { getCategoryRequestSnapshot, parseCategoryRequests, saveCategoryRequests, subscribeCategoryRequests } from "@/services/category-request-storage";
import { slugify } from "@/utils/slugify";

export function CategoryForm({ categoryId }: { categoryId?: string }) {
  const router = useRouter(); const searchParams = useSearchParams(); const { categories, addCategory, updateCategory } = useCategories(); const { recordAction } = useAdmin();
  const requestSnapshot = useSyncExternalStore(subscribeCategoryRequests, getCategoryRequestSnapshot, () => "[]"); const requests = useMemo(() => parseCategoryRequests(requestSnapshot), [requestSnapshot]); const requestId = searchParams.get("requestId"); const request = requestId ? requests.find((item) => item.id === requestId) : undefined; const existing = categoryId ? categories.find((item) => item.id === categoryId) : undefined;
  const [name, setName] = useState(existing?.name ?? request?.suggestedName ?? ""); const [slug, setSlug] = useState(existing?.slug ?? slugify(request?.suggestedName ?? "")); const [description, setDescription] = useState(existing?.description ?? request?.description ?? ""); const [image, setImage] = useState(existing?.image ?? "/products/detail-green.svg"); const [parentCategoryId, setParentCategoryId] = useState(existing?.parentCategoryId ?? ""); const [isActive, setIsActive] = useState(existing?.isActive ?? true); const [error, setError] = useState("");
  if (categoryId && !existing) return <div className="rounded-2xl bg-white p-12 text-center"><h1 className="text-2xl font-black">Category not found</h1><Link href="/admin/categories" className="mt-5 inline-flex rounded-xl bg-emerald-700 px-5 py-3 text-sm font-bold text-white">Back to categories</Link></div>;
  function readImage(file?: File) { if (!file) return; const reader = new FileReader(); reader.onload = () => { if (typeof reader.result === "string") setImage(reader.result); }; reader.readAsDataURL(file); }
  function submit(event: React.FormEvent) { event.preventDefault(); const cleanName = name.trim(); const cleanSlug = slugify(slug); if (!cleanName) return setError("Category name is required."); if (!cleanSlug) return setError("Enter a valid slug."); if (parentCategoryId === existing?.id) return setError("A category cannot be its own parent."); if (categories.some((item) => item.id !== existing?.id && item.name.toLowerCase() === cleanName.toLowerCase())) return setError("A category with this name already exists."); if (categories.some((item) => item.id !== existing?.id && item.slug === cleanSlug)) return setError("This category slug is already in use."); const category: Category = { id: existing?.id ?? `category-${window.crypto.randomUUID()}`, name: cleanName, slug: cleanSlug, description: description.trim(), image, parentCategoryId: parentCategoryId || undefined, isActive, createdAt: existing?.createdAt ?? new Date().toISOString() }; if (existing) updateCategory(existing.id, category); else addCategory(category); if (request) saveCategoryRequests(requests.map((item) => item.id === request.id ? { ...item, status: "Approved" } : item)); recordAction({ actionType: existing ? "Category updated" : "Category created", entityType: "category", entityId: category.id, reason: request ? `Approved seller category request ${request.id}` : "Admin category form submission", previousValue: existing ? JSON.stringify(existing) : undefined, newValue: JSON.stringify(category) }); router.push("/admin/categories"); }
  const input = "mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 font-normal outline-none focus:border-emerald-500";
  return <><div><Link href="/admin/categories" className="text-sm font-bold text-emerald-700">← Categories</Link><h1 className="mt-3 text-3xl font-black">{existing ? "Edit category" : "Add category"}</h1><p className="mt-2 text-sm text-slate-500">Products stay connected by category ID even when category details change.</p></div><form onSubmit={submit} className="mt-7 max-w-3xl rounded-2xl border border-slate-200 bg-white p-5 sm:p-7">{error ? <div role="alert" className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div> : null}{request ? <div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><b>Approving request:</b> {request.reason}</div> : null}<div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Category name<input required value={name} onChange={(event) => { setName(event.target.value); if (!existing) setSlug(slugify(event.target.value)); }} className={input} /></label><label className="text-sm font-bold">Slug<input required value={slug} onChange={(event) => setSlug(event.target.value)} className={input} /></label><label className="text-sm font-bold sm:col-span-2">Description<textarea required rows={4} value={description} onChange={(event) => setDescription(event.target.value)} className={input} /></label><label className="text-sm font-bold">Category image or icon path<input value={image} onChange={(event) => setImage(event.target.value)} className={input} /><input type="file" accept="image/*" onChange={(event) => readImage(event.target.files?.[0])} className="mt-2 block w-full text-xs" /></label><label className="text-sm font-bold">Parent category<select value={parentCategoryId} onChange={(event) => setParentCategoryId(event.target.value)} className={input}><option value="">None (main category)</option>{categories.filter((item) => !item.parentCategoryId && item.id !== existing?.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="flex items-center gap-3 text-sm font-bold sm:col-span-2"><input type="checkbox" checked={isActive} onChange={(event) => setIsActive(event.target.checked)} className="size-5 accent-emerald-700" />Category is active</label></div><div className="mt-7 flex justify-end gap-3 border-t border-slate-100 pt-5"><Link href="/admin/categories" className="rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold">Cancel</Link><button type="submit" className="rounded-xl bg-emerald-700 px-6 py-3 text-sm font-black text-white">Save Category</button></div></form></>;
}
