"""create core marketplace tables

Revision ID: 4a646941a0e8
Revises: ca4dcc2a0b5d
Create Date: 2026-08-03 20:50:13.211481
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '4a646941a0e8'
down_revision: str | Sequence[str] | None = 'ca4dcc2a0b5d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
