"""add authentication support

Revision ID: f78132ad79ff
Revises: 0a8b302bc210
Create Date: 2026-08-03 21:09:32.914697
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'f78132ad79ff'
down_revision: str | Sequence[str] | None = '0a8b302bc210'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
