"use client";

import type { DeliveryInformation } from "@/types";

const locations = ["Accra, Greater Accra", "Tema, Greater Accra", "Kumasi, Ashanti", "Cape Coast, Central", "Takoradi, Western", "Koforidua, Eastern", "Tamale, Northern"];

export function DeliveryForm({ value, onChange }: { value: DeliveryInformation; onChange: (value: DeliveryInformation) => void }) {
  const input = "mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 font-normal outline-none focus:border-emerald-500";
  return <fieldset><legend className="text-sm font-black text-slate-800">Delivery information</legend><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700 sm:col-span-2">Product location<select value={value.location} onChange={(event) => onChange({ ...value, location: event.target.value })} className={input}>{locations.map((location) => <option key={location}>{location}</option>)}</select></label><label className="flex items-center gap-3 rounded-xl border border-slate-200 p-4 text-sm font-bold"><input type="checkbox" checked={value.deliveryAvailable} onChange={(event) => onChange({ ...value, deliveryAvailable: event.target.checked })} className="size-4 accent-emerald-700" />Delivery available</label><label className="flex items-center gap-3 rounded-xl border border-slate-200 p-4 text-sm font-bold"><input type="checkbox" checked={value.pickupAvailable} onChange={(event) => onChange({ ...value, pickupAvailable: event.target.checked })} className="size-4 accent-emerald-700" />Pickup available</label><label className="text-sm font-bold">Standard fee (GH₵)<input type="number" min="0" value={value.standardDeliveryFee} onChange={(event) => onChange({ ...value, standardDeliveryFee: Number(event.target.value) })} className={input} /></label><label className="text-sm font-bold">Express fee (GH₵)<input type="number" min="0" value={value.expressDeliveryFee} onChange={(event) => onChange({ ...value, expressDeliveryFee: Number(event.target.value) })} className={input} /></label><label className="text-sm font-bold sm:col-span-2">Estimated delivery days<input type="number" min="1" value={value.estimatedDeliveryDays} onChange={(event) => onChange({ ...value, estimatedDeliveryDays: Number(event.target.value) })} className={input} /></label></div></fieldset>;
}
