"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import { PlusIcon } from "@/components/common/icons";
import { ConfirmationModal } from "@/components/orders/confirmation-modal";
import { StatusBadge } from "@/components/seller/status-badge";
import { useCategories } from "@/context/category-context";
import { useProducts } from "@/context/product-context";
import { currentSeller } from "@/data/current-seller";
import { useOrders } from "@/hooks/use-orders";
import type { Product } from "@/types";
import { formatCurrency } from "@/utils/format-currency";
import { getProductStatus } from "@/utils/product-status";

export function SellerProductsPage() {
  const { products, deleteProduct, toggleProductActive } = useProducts();
  const { categories } = useCategories();
  const { orders } = useOrders();
  const [search, setSearch] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [status, setStatus] = useState("");
  const [stock, setStock] = useState("");
  const [sort, setSort] = useState("newest");
  const [deleteTarget, setDeleteTarget] = useState<Product | null>(null);
  const [notice, setNotice] = useState("");
  const sellerProducts = useMemo(() => products.filter((product) => product.seller.id === currentSeller.id).filter((product) => !search || product.name.toLowerCase().includes(search.toLowerCase())).filter((product) => !categoryId || product.categoryId === categoryId).filter((product) => !status || getProductStatus(product) === status).filter((product) => !stock || (stock === "in" ? product.stock > 0 : stock === "low" ? product.stock > 0 && product.stock <= (product.lowStockThreshold ?? 5) : product.stock === 0)).sort((a, b) => sort === "oldest" ? Date.parse(a.createdAt) - Date.parse(b.createdAt) : sort === "price-high" ? b.price - a.price : sort === "stock-low" ? a.stock - b.stock : Date.parse(b.createdAt) - Date.parse(a.createdAt)), [products, search, categoryId, status, stock, sort]);
  const mainCategories = categories.filter((category) => !category.parentCategoryId);
  const categoryName = (id?: string) => categories.find((category) => category.id === id)?.name ?? "—";
  function requestDelete(product: Product) {
    const activeOrder = orders.some((order) => !["Completed", "Cancelled", "Refunded"].includes(order.status) && order.items.some((item) => item.productId === product.id));
    if (activeOrder) { setNotice(`${product.name} is connected to an active order and cannot be deleted. Deactivate it instead.`); return; }
    setDeleteTarget(product);
  }
  const ProductActions = ({ product }: { product: Product }) => <div className="flex flex-wrap gap-2"><Link href={`/seller/products/${product.id}`} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold">View</Link><Link href={`/seller/products/${product.id}/edit`} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold">Edit</Link><button type="button" onClick={() => toggleProductActive(product.id)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold">{getProductStatus(product) === "Active" ? "Deactivate" : "Activate"}</button><button type="button" onClick={() => requestDelete(product)} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700">Delete</button></div>;
  return <>
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-emerald-700">{currentSeller.storeName}</p><h1 className="mt-1 text-3xl font-black">Products</h1><p className="mt-2 text-sm text-slate-500">Manage every product belonging to your store.</p></div><Link href="/seller/products/new" className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 text-sm font-black text-white"><PlusIcon className="size-4" />Add Product</Link></div>
    {notice ? <div role="alert" className="mt-6 flex justify-between rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-bold text-amber-800"><span>{notice}</span><button type="button" onClick={() => setNotice("")} aria-label="Dismiss">×</button></div> : null}
    <div className="mt-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-2 xl:grid-cols-5"><label className="text-xs font-bold">Search<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Product name" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal" /></label><label className="text-xs font-bold">Category<select value={categoryId} onChange={(event) => setCategoryId(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal"><option value="">All categories</option>{mainCategories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="text-xs font-bold">Status<select value={status} onChange={(event) => setStatus(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal"><option value="">All statuses</option>{["Draft", "Pending Review", "Active", "Inactive", "Rejected", "Out of Stock"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-xs font-bold">Stock<select value={stock} onChange={(event) => setStock(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal"><option value="">All stock</option><option value="in">In stock</option><option value="low">Low stock</option><option value="out">Out of stock</option></select></label><label className="text-xs font-bold">Sort<select value={sort} onChange={(event) => setSort(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="price-high">Highest price</option><option value="stock-low">Lowest stock</option></select></label></div>
    {sellerProducts.length ? <><div className="mt-6 hidden overflow-x-auto rounded-2xl border border-slate-200 bg-white md:block"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Product</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Stock</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Performance</th><th className="px-4 py-3">Created</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{sellerProducts.map((product) => <tr key={product.id}><td className="px-4 py-4"><div className="flex items-center gap-3"><div className="relative size-12 overflow-hidden rounded-lg bg-slate-100"><Image src={product.images[0]} alt="" fill sizes="48px" className="object-cover" /></div><span className="max-w-56 font-black">{product.name}</span></div></td><td className="px-4 py-4 text-xs text-slate-600">{categoryName(product.categoryId)}<br /><span className="text-slate-400">{categoryName(product.subcategoryId)}</span></td><td className="px-4 py-4 font-black">{formatCurrency(product.price)}</td><td className="px-4 py-4">{product.stock}</td><td className="px-4 py-4"><StatusBadge status={getProductStatus(product)} /></td><td className="px-4 py-4 text-xs text-slate-500">{product.views ?? 0} views<br />{product.sales ?? 0} sales</td><td className="px-4 py-4 text-xs">{new Date(product.createdAt).toLocaleDateString("en-GH")}</td><td className="px-4 py-4"><ProductActions product={product} /></td></tr>)}</tbody></table></div><div className="mt-6 grid gap-4 md:hidden">{sellerProducts.map((product) => <article key={product.id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex gap-3"><div className="relative size-20 shrink-0 overflow-hidden rounded-xl bg-slate-100"><Image src={product.images[0]} alt="" fill sizes="80px" className="object-cover" /></div><div className="min-w-0"><h2 className="font-black">{product.name}</h2><p className="mt-1 text-xs text-slate-500">{categoryName(product.categoryId)} · {formatCurrency(product.price)}</p><div className="mt-2"><StatusBadge status={getProductStatus(product)} /></div></div></div><div className="my-4 grid grid-cols-3 gap-2 rounded-xl bg-slate-50 p-3 text-center text-xs"><div><b className="block text-sm">{product.stock}</b>Stock</div><div><b className="block text-sm">{product.views ?? 0}</b>Views</div><div><b className="block text-sm">{product.sales ?? 0}</b>Sales</div></div><ProductActions product={product} /></article>)}</div></> : <div className="mt-6 rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><h2 className="text-xl font-black">No products found</h2><p className="mt-2 text-sm text-slate-500">Adjust your filters or add a new product.</p></div>}
    <ConfirmationModal isOpen={Boolean(deleteTarget)} title="Delete this product?" description="Products connected to active orders cannot be deleted. This product will be permanently removed from the local marketplace data." confirmLabel="Delete Product" onClose={() => setDeleteTarget(null)} onConfirm={() => { if (deleteTarget) deleteProduct(deleteTarget.id); setDeleteTarget(null); }} />
  </>;
}
